
(()=>{'use strict';
const products=[
 {id:'torta-pistacho',name:'Torta de Pistacho',description:'Ponqué de textura suave con una cubierta de chocolate blanco y pistacho.',price:8,category:'saludables',label:'Tortas saludables',image:'assets/torta-pistacho.jpg'},
 {id:'ponque-chocolate',name:'Ponqué Chocolate Anella',description:'Ponqué con textura suave doble capa, cubierto con chocolate y almendra.',price:8,category:'saludables',label:'Tortas saludables',image:'assets/ponque-chocolate-anella.jpg'},
 {id:'torta-zanahoria',name:'Torta Zanahoria',description:'Ponqué con textura húmeda cubierta de yogurt griego con nueces.',price:8,category:'saludables',label:'Tortas saludables',image:'assets/torta-zanahoria.jpg'},
 {id:'pie-pistacho',name:'Pie de Pistacho',description:'Base de galleta con una capa de crema de pistacho con mousse de chocolate.',price:8,category:'frias',label:'Tortas frías',image:'assets/pie-pistacho.jpg'},
 {id:'cheesecake-frutos-rojos',name:'Cheesecake de Frutos Rojos',description:'Base de avena con queso crema con una capa de frutos rojos.',price:7,category:'frias',label:'Tortas frías',image:'assets/cheesecake-frutos-rojos.jpg'},
 {id:'brownie',name:'Brownie',description:'Torta cremosa de textura húmeda cubierta de chocolate y almendras picadas.',price:8,category:'saludables',label:'Tortas saludables',image:'assets/brownie.jpg'}
];
const key='anella-demo-cart-v1',euro=n=>new Intl.NumberFormat('es-ES',{style:'currency',currency:'EUR'}).format(n),$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],escapeHTML=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
let activeFilter='all',cart={},activePanel=null,lastFocused=null;try{cart=JSON.parse(localStorage.getItem(key)||'{}')||{}}catch{cart={}}
function count(){return Object.values(cart).reduce((a,b)=>a+Number(b||0),0)}
function subtotal(){return products.reduce((sum,p)=>sum+(cart[p.id]||0)*p.price,0)}
function save(){localStorage.setItem(key,JSON.stringify(cart));renderCart()}
function renderProducts(){const q=$('#search').value.trim().toLocaleLowerCase('es');const list=products.filter(p=>(activeFilter==='all'||p.category===activeFilter)&&(p.name+' '+p.description).toLocaleLowerCase('es').includes(q));const noun=list.length===1?'postre':'postres',state=q||activeFilter!=='all'?(list.length===1?'encontrado':'encontrados'):'disponibles';$('#resultSummary').textContent=`${list.length} ${noun} ${state}`;$('#productGrid').innerHTML=list.length?list.map(p=>`<article class="product-card" data-product-id="${p.id}"><div class="product-image"><img src="${p.image}" alt="Imagen ilustrativa generada de ${p.name}" loading="lazy"><span class="image-badge">Imagen ilustrativa</span></div><div class="product-body"><span class="product-kicker">${p.label}</span><h3>${p.name}</h3><p>${p.description}</p><div class="product-foot"><span class="price">${euro(p.price)}</span><button class="btn btn-petrol small-btn" data-detail="${p.id}">Ver detalle</button></div></div></article>`).join(''):'<div class="empty"><strong>No encontramos postres con esos criterios.</strong><br>Prueba otra búsqueda o vuelve a ver toda la carta.<br><button class="btn btn-petrol small-btn" type="button" data-reset-catalog>Ver todos los postres</button></div>'}
function renderCart(){const entries=products.filter(p=>cart[p.id]);$('#cartCount').textContent=count();$('#subtotal').textContent=euro(subtotal());$('#cartItems').innerHTML=entries.length?entries.map(p=>`<div class="line-item"><img src="${p.image}" alt=""><div><strong>${p.name}</strong><small>${euro(p.price)} unidad</small><div class="qty" aria-label="Cantidad de ${p.name}"><button data-qty="${p.id}" data-delta="-1" aria-label="Quitar una unidad">−</button><span>${cart[p.id]}</span><button data-qty="${p.id}" data-delta="1" aria-label="Añadir una unidad">+</button></div></div><strong>${euro(p.price*cart[p.id])}</strong></div>`).join(''):'<div class="empty"><strong>Tu carrito está vacío.</strong><br>Elige un postre para comenzar.</div>';$('#checkoutButton').disabled=!entries.length;if(!entries.length)$('#checkoutArea').innerHTML=''}
function hidePanels(){$$('.drawer,.modal').forEach(el=>{el.classList.remove('open');el.setAttribute('aria-hidden','true')});$('#overlay').classList.remove('open')}
function setPageInert(value){$$('[data-page-shell]').forEach(el=>{if(value){el.setAttribute('inert','');el.setAttribute('aria-hidden','true')}else{el.removeAttribute('inert');el.removeAttribute('aria-hidden')}})}
function closeAll(){const returnTo=lastFocused;hidePanels();activePanel=null;lastFocused=null;setPageInert(false);document.body.classList.remove('locked');if(returnTo&&returnTo.isConnected)requestAnimationFrame(()=>returnTo.focus())}
function openPanel(el){if(!activePanel)lastFocused=document.activeElement;hidePanels();activePanel=el;el.classList.add('open');el.setAttribute('aria-hidden','false');$('#overlay').classList.add('open');setPageInert(true);document.body.classList.add('locked');setTimeout(()=>{const target=el.querySelector('button:not(:disabled),input:not(:disabled)');if(target)target.focus()},20)}
function showDetail(id){const p=products.find(x=>x.id===id);$('#detailBody').innerHTML=`<div class="detail-grid"><img src="${p.image}" alt="Imagen ilustrativa generada de ${p.name}"><div class="detail-copy"><span class="product-kicker">${p.label}</span><h3 id="detailTitle">${p.name}</h3><div class="price">${euro(p.price)}</div><p>${p.description}</p><p><small>Imagen ilustrativa generada para esta propuesta.</small></p><div class="field detail-qty"><label for="detailQty">Cantidad</label><input id="detailQty" type="number" min="1" max="20" value="1"></div><button class="btn btn-petrol" id="addFromDetail" data-product="${p.id}">Añadir al carrito</button></div></div>`;openPanel($('#detailModal'))}
function checkout(){if(!count())return;$('#checkoutArea').innerHTML=`<form id="orderForm" novalidate><h3>¿Cómo lo recibirías?</h3><div class="notice">Pedido completamente simulado. No se enviará información ni se conectará con Anella.</div><div class="form-grid"><fieldset class="fieldset"><legend>Modalidad</legend><label><input type="radio" name="mode" value="Pickup" checked> Pickup</label><label><input type="radio" name="mode" value="Delivery"> Delivery</label></fieldset><div class="field full" id="addressWrap" hidden><label for="address">Dirección de entrega *</label><input id="address" name="address" autocomplete="street-address"></div><div class="field full"><label for="notes">Notas (opcional)</label><textarea id="notes" name="notes"></textarea></div><div class="field full"><label><input id="acceptSimulation" type="checkbox"> Acepto que este pedido es solo una simulación y no se enviará.</label></div></div><div class="error" id="orderError" role="alert"></div><button class="btn btn-primary" type="submit" style="width:100%">Ver vista previa</button></form>`;const form=$('#orderForm');form.addEventListener('change',e=>{if(e.target.name==='mode'){const delivery=e.target.value==='Delivery';$('#addressWrap').hidden=!delivery;$('#address').required=delivery}});form.addEventListener('submit',previewOrder)}
function previewOrder(e){e.preventDefault();const fd=new FormData(e.currentTarget),mode=fd.get('mode'),address=$('#address').value.trim();let error='';if(mode==='Delivery'&&!address)error='Indica una dirección para continuar con delivery.';else if(!$('#acceptSimulation').checked)error='Acepta que este pedido es una simulación.';$('#orderError').textContent=error;if(error)return;const lines=products.filter(p=>cart[p.id]).map(p=>`${cart[p.id]} × ${p.name} — ${euro(cart[p.id]*p.price)}`).join('\n');const preview=`PEDIDO SIMULADO · ANELLA CAFÉ\n\n${lines}\n\nSubtotal: ${euro(subtotal())}\nModalidad: ${mode}${address?'\nDirección: '+address:''}${fd.get('notes')?'\nNotas: '+fd.get('notes'):''}`;$('#checkoutArea').innerHTML=`<h3>Vista previa</h3><div class="notice">Revisa tu selección. Nada será enviado.</div><div class="preview">${escapeHTML(preview)}</div><button class="btn btn-petrol" id="confirmOrder" style="width:100%">Confirmar pedido simulado</button>`;$('#confirmOrder').addEventListener('click',confirmOrder)}
function confirmOrder(){const previousTotal=subtotal();cart={};save();$('#confirmationBody').innerHTML=`<div class="success"><div class="success-mark" aria-hidden="true">✓</div><h3>Simulación confirmada</h3><p>Subtotal revisado: <strong>${euro(previousTotal)}</strong></p><p>No se realizó ningún pedido, pago o envío de información.</p><button class="btn btn-petrol" data-close>Volver a la tienda</button></div>`;openPanel($('#confirmationModal'))}
document.addEventListener('click',e=>{const detail=e.target.closest('[data-detail]');if(detail)showDetail(detail.dataset.detail);if(e.target.closest('[data-open-cart]'))openPanel($('#cartDrawer'));if(e.target.closest('[data-close]'))closeAll();const adjust=e.target.closest('[data-qty]');if(adjust){cart[adjust.dataset.qty]=Math.max(0,(cart[adjust.dataset.qty]||0)+Number(adjust.dataset.delta));if(!cart[adjust.dataset.qty])delete cart[adjust.dataset.qty];save()}const add=e.target.closest('#addFromDetail');if(add){const quantity=Math.max(1,Math.min(20,Number($('#detailQty').value)||1));cart[add.dataset.product]=(cart[add.dataset.product]||0)+quantity;save();openPanel($('#cartDrawer'))}const chip=e.target.closest('[data-filter]');if(chip){$$('[data-filter]').forEach(x=>{x.classList.remove('active');x.setAttribute('aria-pressed','false')});chip.classList.add('active');chip.setAttribute('aria-pressed','true');activeFilter=chip.dataset.filter;renderProducts()}if(e.target.closest('[data-reset-catalog]')){$('#search').value='';activeFilter='all';$$('[data-filter]').forEach(x=>{const active=x.dataset.filter==='all';x.classList.toggle('active',active);x.setAttribute('aria-pressed',String(active))});renderProducts();$('#search').focus()}});
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&activePanel){closeAll();return}if(e.key==='Tab'&&activePanel){const focusable=[...activePanel.querySelectorAll('button:not(:disabled),input:not(:disabled),textarea:not(:disabled),a[href]')].filter(el=>!el.hidden&&el.offsetParent!==null);if(!focusable.length)return;const first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});$('#search').addEventListener('input',renderProducts);$('#checkoutButton').addEventListener('click',checkout);renderProducts();renderCart();
})();
