const {chromium}=require('playwright-core');
const fs=require('fs'),path=require('path');
const base=process.env.QA_URL;if(!base)throw new Error('QA_URL required');
const root=path.resolve(__dirname,'..'),shots=path.join(__dirname,'screenshots');fs.mkdirSync(shots,{recursive:true});
const expected=[['Torta de Pistacho',8],['Ponqué Chocolate Anella',8],['Torta Zanahoria',8],['Pie de Pistacho',8],['Cheesecake de Frutos Rojos',7],['Brownie',8]];
const report={url:base,runAt:new Date().toISOString(),viewports:{},gates:{},metrics:{},consoleErrors:[],pageErrors:[],failedRequests:[],offOriginRequests:[],screenshots:[]};
const assert=(cond,name,detail='')=>{report.gates[name]=(report.gates[name]??true)&&!!cond;if(!cond)throw new Error(`${name}: ${detail}`)};
const money=async p=>await p.locator('#subtotal').textContent();
async function overflow(page,label){const v=await page.evaluate(()=>({doc:document.documentElement.scrollWidth,client:document.documentElement.clientWidth,body:document.body.scrollWidth}));assert(v.doc<=v.client+1&&v.body<=v.client+1,`noOverflow_${label}`,JSON.stringify(v));return v}
async function settle(page,selector){await page.locator(selector).evaluate(el=>Promise.all(el.getAnimations({subtree:true}).map(a=>a.finished.catch(()=>{}))))}
async function shot(page,device,state){const file=`${device}-${state}.png`;await page.screenshot({path:path.join(shots,file),fullPage:state==='catalog'});report.screenshots.push(`qa/screenshots/${file}`)}
async function run(browser,device,viewport){const context=await browser.newContext({viewport,deviceScaleFactor:1,colorScheme:'light'});await context.addInitScript(()=>{if(!sessionStorage.getItem('anella-qa-started')){localStorage.removeItem('anella-demo-cart-v1');sessionStorage.setItem('anella-qa-started','1')}});const page=await context.newPage();const origin=new URL(base).origin;
 page.on('console',m=>{if(m.type()==='error')report.consoleErrors.push({device,text:m.text()})});page.on('pageerror',e=>report.pageErrors.push({device,text:e.message}));page.on('requestfailed',r=>report.failedRequests.push({device,url:r.url(),error:r.failure()?.errorText}));page.on('request',r=>{if(new URL(r.url()).origin!==origin)report.offOriginRequests.push({device,url:r.url()})});
 await page.goto(base,{waitUntil:'networkidle'});
 assert(await page.locator('.demo-bar').isVisible(),`disclosure_${device}`);assert(await page.locator('.product-card').count()===6,`productCount_${device}`);await overflow(page,`${device}_home`);await shot(page,device,'home');
 await page.locator('#catalogo').scrollIntoViewIfNeeded();await shot(page,device,'catalog');
 await page.locator('#search').fill('Brownie');assert(await page.locator('.product-card').count()===1,`search_${device}`);assert((await page.locator('.product-card h3').textContent()).trim()==='Brownie',`searchResult_${device}`);await page.locator('#search').fill('');
 await page.getByRole('button',{name:'Tortas frías'}).click();assert(await page.locator('.product-card').count()===2,`filterCold_${device}`);await page.getByRole('button',{name:'Tortas saludables'}).click();assert(await page.locator('.product-card').count()===4,`filterHealthy_${device}`);await page.getByRole('button',{name:'Todos'}).click();assert(await page.locator('.product-card').count()===6,`filterAll_${device}`);
 await page.locator('[data-detail="torta-pistacho"]').click();await page.locator('#detailModal.open').waitFor();await settle(page,'#detailModal');assert(await page.locator('#detailTitle').textContent()==='Torta de Pistacho',`detail_${device}`);await shot(page,device,'detail');await page.locator('#detailQty').fill('1');await page.locator('#addFromDetail').click();await page.locator('#cartDrawer.open').waitFor();await page.locator('#cartDrawer [data-close]').click();
 await page.locator('[data-detail="ponque-chocolate"]').click();await page.locator('#detailQty').fill('1');await page.locator('#addFromDetail').click();await page.locator('#cartDrawer.open').waitFor();await settle(page,'#cartDrawer');assert(await page.locator('.line-item').count()===2,`twoDifferentProducts_${device}`);assert((await money(page)).includes('16,00'),`subtotal_${device}`,await money(page));await shot(page,device,'cart');
 await page.reload({waitUntil:'networkidle'});assert(await page.locator('#cartCount').textContent()==='2',`persistence_${device}`);await page.locator('[data-open-cart]').click();assert(await page.locator('.line-item').count()===2,`persistenceItems_${device}`);assert((await money(page)).includes('16,00'),`persistenceSubtotal_${device}`);
 await page.locator('#checkoutButton').click();await page.getByRole('button',{name:'Ver vista previa'}).click();assert((await page.locator('#orderError').textContent()).includes('simulación'),`simulationAcceptanceRequired_${device}`);await page.getByLabel('Delivery').check();await page.locator('#acceptSimulation').check();await page.getByRole('button',{name:'Ver vista previa'}).click();assert((await page.locator('#orderError').textContent()).includes('dirección'),`deliveryBlockedWithoutAddress_${device}`);assert(await page.locator('#orderForm').count()===1,`blockedKeepsForm_${device}`);
 await page.locator('#address').fill('Calle de prueba 123');await page.getByRole('button',{name:'Ver vista previa'}).click();assert(await page.getByText('PEDIDO SIMULADO · ANELLA CAFÉ').isVisible(),`deliveryAllowedWithAddress_${device}`);assert((await page.locator('.preview').textContent()).includes('16,00'),`previewSubtotal_${device}`);await page.getByRole('button',{name:'Confirmar pedido simulado'}).click();await page.locator('#confirmationModal.open').waitFor();await settle(page,'#confirmationModal');assert(await page.getByText('Simulación confirmada').isVisible(),`confirmation_${device}`);assert((await page.locator('#confirmationBody').textContent()).includes('16,00'),`confirmationSubtotal_${device}`);await overflow(page,`${device}_confirmation`);await shot(page,device,'confirmation');assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('anella-demo-cart-v1')||'{}')),`storageReadable_${device}`);
 report.viewports[device]={...viewport,overflow:false};await context.close()}
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'});let fatal='';try{await run(browser,'desktop',{width:1440,height:1000});await run(browser,'mobile',{width:390,height:844})}catch(e){fatal=e.stack||String(e)}finally{await browser.close()}
 report.gates.zeroConsoleErrors=report.consoleErrors.length===0;report.gates.zeroPageErrors=report.pageErrors.length===0;report.gates.zeroFailedRequests=report.failedRequests.length===0;report.gates.zeroOffOriginRequests=report.offOriginRequests.length===0;report.gates.screenshotCount=report.screenshots.length===10;report.metrics={expectedProducts:expected.length,screenshotCount:report.screenshots.length,testedViewports:2,expectedTwoItemSubtotal:'16,00 €'};report.fatalError=fatal||null;const failed=Object.entries(report.gates).filter(([,v])=>!v).map(([k])=>k);report.failedGates=failed;report.status=!fatal&&!failed.length?'pass':'fail';fs.writeFileSync(path.join(__dirname,'qa-report.json'),JSON.stringify(report,null,2)+'\n');console.log(JSON.stringify(report,null,2));process.exit(report.status==='pass'?0:1)})();
